samples/WebApplicationSample/Models/WeChatPayV3ViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplicationSample.Models
{
    public class WeChatPayAppPayV3ViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Required]
        [Display(Name = "description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "total")]
        public int Total { get; set; }

        [Required]
        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }
    }

    public class WeChatPayPubPayV3ViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Required]
        [Display(Name = "description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "total")]
        public int Total { get; set; }

        [Required]
        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }

        [Required]
        [Display(Name = "openid")]
        public string OpenId { get; set; }
    }

    public class WeChatPayQrCodePayV3ViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Required]
        [Display(Name = "description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "total")]
        public int Total { get; set; }

        [Required]
        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }
    }

    public class WeChatPayH5PayV3ViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Required]
        [Display(Name = "description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "total")]
        public int Total { get; set; }

        [Required]
        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }
    }

    public class WeChatPayQueryByTransactionIdViewModel
    {
        [Required]
        [Display(Name = "transaction_id")]
        public string TransactionId { get; set; }
    }

    public class WeChatPayQueryByOutTradeNoViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }
    }

    public class WeChatPayOutTradeNoCloseViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }
    }

    public class WeChatPayTradeBillViewModel
    {
        [Required]
        [Display(Name = "bill_date")]
        public string BillDate { get; set; }
    }

    public class WeChatPayFundflowBillViewModel
    {
        [Required]
        [Display(Name = "bill_date")]
        public string BillDate { get; set; }
    }

    public class WeChatPayBillDownloadViewModel
    {
        [Required]
        [Display(Name = "download_url")]
        public string DownloadUrl { get; set; }
    }
}

samples/WebApplicationSample/Controllers/WeChatPayV3Controller.cs
using System.Text.Json;
using System.Threading.Tasks;
using Essensoft.AspNetCore.Payment.WeChatPay;
using Essensoft.AspNetCore.Payment.WeChatPay.V3;
using Essensoft.AspNetCore.Payment.WeChatPay.V3.Domain;
using Essensoft.AspNetCore.Payment.WeChatPay.V3.Request;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplicationSample.Models;

namespace WebApplicationSample.Controllers
{
    public class WeChatPayV3Controller : Controller
    {
        private readonly IWeChatPayClient _client;
        private readonly IOptions<WeChatPayOptions> _optionsAccessor;

        public WeChatPayV3Controller(IWeChatPayClient client, IOptions<WeChatPayOptions> optionsAccessor)
        {
            _client = client;
            _optionsAccessor = optionsAccessor;
        }

        /// <summary>
        /// 微信支付指引页
        /// </summary>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取平台证书列表
        /// </summary>
        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> GetCertificates()
        {
            if (Request.Method == "POST")
            {
                var request = new WeChatPayCertificatesRequest();
                var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
                ViewData["response"] = response.Body;
                return View();
            }

            return View();
        }

        /// <summary>
        /// APP支付-App下单API
        /// </summary>
        [HttpGet]
        public IActionResult AppPay()
        {
            return View();
        }

        /// <summary>
        /// APP支付-App下单API
        /// </summary>
        /// <param name="viewModel"></param>
        [HttpPost]
        public async Task<IActionResult> AppPay(WeChatPayAppPayV3ViewModel viewModel)
        {
            var model = new WeChatPayTransactionsAppModel
            {
                AppId = _optionsAccessor.Value.AppId,
                MchId = _optionsAccessor.Value.MchId,
                Amount = new Amount { Total = viewModel.Total, Currency = "CNY" },
                Description = viewModel.Description,
                NotifyUrl = viewModel.NotifyUrl,
                OutTradeNo = viewModel.OutTradeNo,
            };

            var request = new WeChatPayTransactionsAppRequest();
            request.SetQueryModel(model);

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);

            if (response.StatusCode == 200)
            {
                var req = new WeChatPayAppSdkRequest
                {
                    PrepayId = response.PrepayId
                };

                var parameter = await _client.ExecuteAsync(req, _optionsAccessor.Value);

                // 将参数(parameter)给 ios/android端 
                // https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter3_7.shtml
                ViewData["parameter"] = JsonSerializer.Serialize(parameter);
                ViewData["response"] = response.Body;
                return View();
            }

            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 公众号支付-JSAPI下单
        /// </summary>
        [HttpGet]
        public IActionResult PubPay()
        {
            return View();
        }

        /// <summary>
        /// 公众号支付-JSAPI下单
        /// </summary>
        /// <param name="viewModel"></param>
        [HttpPost]
        public async Task<IActionResult> PubPay(WeChatPayPubPayV3ViewModel viewModel)
        {
            var model = new WeChatPayTransactionsJsApiModel
            {
                AppId = _optionsAccessor.Value.AppId,
                MchId = _optionsAccessor.Value.MchId,
                Amount = new Amount { Total = viewModel.Total, Currency = "CNY" },
                Description = viewModel.Description,
                NotifyUrl = viewModel.NotifyUrl,
                OutTradeNo = viewModel.OutTradeNo,
                Payer = new PayerInfo { OpenId = viewModel.OpenId }
            };

            var request = new WeChatPayTransactionsJsApiRequest();
            request.SetQueryModel(model);

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);

            if (response.StatusCode == 200)
            {
                var req = new WeChatPayJsApiSdkRequest
                {
                    Package = "prepay_id=" + response.PrepayId
                };

                var parameter = await _client.ExecuteAsync(req, _optionsAccessor.Value);

                // 将参数(parameter)给 公众号前端
                // https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter3_8.shtml
                ViewData["parameter"] = JsonSerializer.Serialize(parameter);
                ViewData["response"] = response.Body;
                return View();
            }

            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 扫码支付-Native下单API
        /// </summary>
        [HttpGet]
        public IActionResult QrCodePay()
        {
            return View();
        }

        /// <summary>
        /// 扫码支付-Native下单API
        /// </summary>
        /// <param name="viewModel"></param>
        [HttpPost]
        public async Task<IActionResult> QrCodePay(WeChatPayQrCodePayV3ViewModel viewModel)
        {
            var model = new WeChatPayTransactionsNativeModel
            {
                AppId = _optionsAccessor.Value.AppId,
                MchId = _optionsAccessor.Value.MchId,
                Amount = new Amount { Total = viewModel.Total, Currency = "CNY" },
                Description = viewModel.Description,
                NotifyUrl = viewModel.NotifyUrl,
                OutTradeNo = viewModel.OutTradeNo,
            };

            var request = new WeChatPayTransactionsNativeRequest();
            request.SetQueryModel(model);

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);

            // response.CodeUrl 给前端生成二维码
            ViewData["qrcode"] = response.CodeUrl;
            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// H5支付-H5下单API
        /// </summary>
        [HttpGet]
        public IActionResult H5Pay()
        {
            return View();
        }

        /// <summary>
        /// H5支付-H5下单API
        /// </summary>
        /// <param name="viewModel"></param>
        [HttpPost]
        public async Task<IActionResult> H5Pay(WeChatPayH5PayV3ViewModel viewModel)
        {
            var model = new WeChatPayTransactionsH5Model
            {
                AppId = _optionsAccessor.Value.AppId,
                MchId = _optionsAccessor.Value.MchId,
                Amount = new Amount { Total = viewModel.Total, Currency = "CNY" },
                Description = viewModel.Description,
                NotifyUrl = viewModel.NotifyUrl,
                OutTradeNo = viewModel.OutTradeNo,
                SceneInfo = new SceneInfo { PayerClientIp = "127.0.0.1" }
            };

            var request = new WeChatPayTransactionsH5Request();
            request.SetQueryModel(model);

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);

            // h5_url为拉起微信支付收银台的中间页面，可通过访问该url来拉起微信客户端，完成支付,h5_url的有效期为5分钟。
            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 微信支付订单号查询
        /// </summary>
        [HttpGet]
        public IActionResult QueryByTransactionId()
        {
            return View();
        }

        /// <summary>
        /// 微信支付订单号查询
        /// </summary>
        /// <param name="viewModel"></param>
        [HttpPost]
        public async Task<IActionResult> QueryByTransactionId(WeChatPayQueryByTransactionIdViewModel viewModel)
        {
            var request = new WeChatPayTransactionsIdRequest
            {
                TransactionId = viewModel.TransactionId,
                MchId = _optionsAccessor.Value.MchId,
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);

            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 商户订单号查询
        /// </summary>
        [HttpGet]
        public IActionResult QueryByOutTradeNo()
        {
            return View();
        }

        /// <summary>
        /// 商户订单号查询
        /// </summary>
        /// <param name="viewModel"></param>
        [HttpPost]
        public async Task<IActionResult> QueryByOutTradeNo(WeChatPayQueryByOutTradeNoViewModel viewModel)
        {
            var request = new WeChatPayTransactionsOutTradeNoRequest
            {
                OutTradeNo = viewModel.OutTradeNo,
                MchId = _optionsAccessor.Value.MchId,
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);

            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 关闭订单
        /// </summary>
        [HttpGet]
        public IActionResult OutTradeNoClose()
        {
            return View();
        }

        /// <summary>
        /// 关闭订单
        /// </summary>
        /// <param name="viewModel"></param>
        [HttpPost]
        public async Task<IActionResult> OutTradeNoClose(WeChatPayOutTradeNoCloseViewModel viewModel)
        {
            var model = new WeChatPayTransactionsOutTradeNoCloseModel
            {
                MchId = _optionsAccessor.Value.MchId,
            };

            var request = new WeChatPayTransactionsOutTradeNoCloseRequest
            {
                OutTradeNo = viewModel.OutTradeNo,
            };

            request.SetQueryModel(model);

samples/WebApplicationSample/Views/WeChatPayV3/AppPay.cshtml
@model WeChatPayAppPayV3ViewModel
@{
    ViewData["Title"] = "APP支付-APP下单API";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPayV3" asp-action="Index">微信支付V3</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPayV3" asp-action="AppPay">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input type="text" class="form-control" asp-for="Description" value="微信APP支付测试" />
            </div>
            <div class="form-group">
                <label asp-for="Total"></label>
                <input type="text" class="form-control" asp-for="Total" value="1" />
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://domain.com/wechatpay/v3/notify/transactions" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
            <div class="form-group">
                <label>Parameter:</label>
                <textarea class="form-control" rows="3">@ViewData["parameter"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/WeChatPayV3/BillDownload.cshtml
@model WeChatPayBillDownloadViewModel
@{
    ViewData["Title"] = "下载账单";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPayV3" asp-action="Index">微信支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPayV3" asp-action="BillDownload">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DownloadUrl"></label>
                <input type="text" class="form-control" asp-for="DownloadUrl" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/WeChatPayV3/FundflowBill.cshtml
@model WeChatPayFundflowBillViewModel
@{
    ViewData["Title"] = "申请交易账单";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPayV3" asp-action="Index">微信支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPayV3" asp-action="FundflowBill">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BillDate"></label>
                <input type="text" class="form-control" asp-for="BillDate" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/WeChatPayV3/GetCertificates.cshtml
@{
    ViewData["Title"] = "获取平台证书列表";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPayV3" asp-action="Index">微信支付V3</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPayV3" asp-action="GetCertificates">
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>

samples/WebApplicationSample/Views/WeChatPayV3/H5Pay.cshtml
@model WeChatPayH5PayV3ViewModel
@{
    ViewData["Title"] = "H5支付-H5下单API";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPayV3" asp-action="Index">微信支付V3</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPayV3" asp-action="H5Pay">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input type="text" class="form-control" asp-for="Description" value="微信H5支付测试" />
            </div>
            <div class="form-group">
                <label asp-for="Total"></label>
                <input type="text" class="form-control" asp-for="Total" value="1">
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://domain.com/wechatpay/v3/notify/transactions">
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/WeChatPayV3/Index.cshtml
@{
    ViewData["Title"] = "微信支付V3";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">首页</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">产品</th>
            <th scope="col">接口</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>获取平台证书列表</td>
            <td><a href="https://wechatpay-api.gitbook.io/wechatpay-api-v3/jie-kou-wen-dang/ping-tai-zheng-shu" target="_blank">https://api.mch.weixin.qq.com/v3/certificates</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="GetCertificates">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>APP支付-App下单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter3_1.shtml" target="_blank">https://api.mch.weixin.qq.com/v3/pay/transactions/app</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="AppPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>公众号支付-JSAPI下单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter3_2.shtml" target="_blank">https://api.mch.weixin.qq.com/v3/pay/transactions/jsapi</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="PubPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <td>扫码支付-Native下单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter3_3.shtml" target="_blank">https://api.mch.weixin.qq.com/v3/pay/transactions/native</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="QrCodePay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <td>H5支付-H5下单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter3_4.shtml" target="_blank">https://api.mch.weixin.qq.com/v3/pay/transactions/h5</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="H5Pay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">6</th>
            <td>查询订单-微信支付订单号查询</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter3_5.shtml" target="_blank">https://api.mch.weixin.qq.com/v3/pay/transactions/id/{transaction_id}</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="QueryByTransactionId">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">7</th>
            <td>查询订单-商户订单号查询</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter3_5.shtml" target="_blank">https://api.mch.weixin.qq.com/v3/pay/transactions/out-trade-no/{out_trade_no}</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="QueryByOutTradeNo">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">8</th>
            <td>关闭订单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter3_6.shtml" target="_blank">https://api.mch.weixin.qq.com/v3/pay/transactions/out-trade-no/{out_trade_no}/close</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="OutTradeNoClose">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">9</th>
            <td>申请交易账单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/bill/chapter3_1.shtml" target="_blank">https://api.mch.weixin.qq.com/v3/bill/tradebill</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="TradeBill">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">10</th>
            <td>申请资金账单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/bill/chapter3_2.shtml" target="_blank">https://api.mch.weixin.qq.com/v3/bill/fundflowbill</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="FundflowBill">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">11</th>
            <td>下载账单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/bill/chapter3_3.shtml" target="_blank">https://api.mch.weixin.qq.com/v3/billdownload/file?token=xxx</a></td>
            <td><a asp-controller="WeChatPayV3" asp-action="BillDownload">立即测试</a></td>
        </tr>
    </tbody>
</table>

samples/WebApplicationSample/Views/WeChatPayV3/OutTradeNoClose.cshtml
@model WeChatPayOutTradeNoCloseViewModel
@{
    ViewData["Title"] = "关闭订单";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPayV3" asp-action="Index">微信支付V3</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPayV3" asp-action="OutTradeNoClose">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/WeChatPayV3/PubPay.cshtml
@model WeChatPayPubPayV3ViewModel
@{
    ViewData["Title"] = "公众号支付-JSAPI下单";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPayV3" asp-action="Index">微信支付V3</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPayV3" asp-action="PubPay">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")">
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input type="text" class="form-control" asp-for="Description" value="微信公众号支付测试">
            </div>
            <div class="form-group">
                <label asp-for="Total"></label>
                <input type="text" class="form-control" asp-for="Total" value="1">
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://domain.com/wechatpay/v3/notify/transactions">
            </div>
            <div class="form-group">
                <label asp-for="OpenId"></label>
                <input type="text" class="form-control" asp-for="OpenId">
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
            <div class="form-group">
                <label>Parameter:</label>
                <textarea class="form-control" rows="3">@ViewData["parameter"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}